# --- Makefile (generated by PyScaffold Clickstart) ----------------------------
# Provides:
#   - Auto versioned builds (setuptools_scm)
#   - Linting/formatting via Ruff
#   - Incremental pytest testing
#   - Release helpers (Git tag based)
# -----------------------------------------------------------------------------

.SILENT:
.ONESHELL:
SHELL := $(shell which bash)
.SHELLFLAGS := -eu -o pipefail -c

# Pick a Python: use 'python' if present, else Windows launcher 'py -3'
PYTHON := $(shell command -v python >/dev/null 2>&1 && echo python || echo py -3)

# Main code package
CODE_DIRS   := src/sfdump
CONF_FILES  := pyproject.toml
STAMPS_DIR  := .stamps
NO_CACHE   ?= 0

# Pytest flags
PYTEST         := $(PYTHON) -m pytest
PYTEST_Q       := -q
PYTEST_WARN    := --disable-warnings
PYTEST_COV     := --cov=sfdump --cov-report=xml --cov-fail-under=40
PYTEST_XDIST   ?= -n auto
PYTEST_TIMEOUT ?= --timeout=60

# Directories
UNIT_DIR := tests/unit
CLI_DIR  := tests/cli
E2E_DIR  := tests/e2e

.PHONY: help bootstrap precommit lint format test test-all build upload \
        version fetch-tags release-show release-patch release-minor release-major \
        clean clean-tests run-cli check-clean

help:
	@echo "Common targets:"
	@echo "  make bootstrap           - install .[dev]"
	@echo "  make precommit           - install pre-commit hook"
	@echo "  make lint                - run Ruff checks"
	@echo "  make format              - auto-fix via Ruff"
	@echo "  make test                - run cached unit tests"
	@echo "  make test-all            - run all tests"
	@echo "  make build               - build wheel+sdist"
	@echo "  make upload              - upload to PyPI (via Twine)"
	@echo "  make version             - print setuptools_scm inferred version"
	@echo "  make release-show        - show scm ver, installed ver, last Git tag"
	@echo "  make release-patch       - tag vX.Y.(Z+1)"
	@echo "  make release-minor       - tag vX.(Y+1).0"
	@echo "  make release-major       - tag v(X+1).0.0"
	@echo "  make clean               - remove build artifacts"
	@echo "  make run-cli             - run CLI entry point"

bootstrap:
	$(PYTHON) -m pip install -U pip setuptools wheel
	$(PYTHON) -m pip install -e ".[dev]"

precommit:
	pre-commit install

# -----------------------------------------------------------------------------#
# Linting / Formatting
lint:
	ruff check .
	ruff format --check .

format:
	ruff check --fix .
	ruff format .

# -----------------------------------------------------------------------------#
# Incremental Testing (simple cache mechanism)
$(STAMPS_DIR):
	mkdir -p $(STAMPS_DIR)

UNIT_STAMP := $(STAMPS_DIR)/unit.ok
UNIT_SIG   := $(STAMPS_DIR)/unit.sig

define compute_dir_sig
{ [ -d "$(1)" ] && find $(1) -type f -not -path "*/__pycache__/*" -print0 || true; } \
| LC_ALL=C sort -z | xargs -0r sha1sum | sha1sum | awk '{print $1}'
endef

$(UNIT_STAMP): | $(STAMPS_DIR)
	@tests_sig=$( $(call compute_dir_sig,$(UNIT_DIR)) ); \
	code_sig=$( $(call compute_dir_sig,$(CODE_DIRS)) ); \
	conf_sig=$( sha1sum $(CONF_FILES) 2>/dev/null | awk '{print $1}' | sha1sum | awk '{print $1}' ); \
	new_sig=$( printf "%s\n%s\n%s\n" "$tests_sig" "$code_sig" "$conf_sig" | sha1sum | awk '{print $1}' ); \
	old_sig=$(cat $(UNIT_SIG) 2>/dev/null || echo -n); \
	if [ "$(NO_CACHE)" = "1" ] || [ "$new_sig" != "$old_sig" ] || [ ! -f $@ ]; then \
	  echo "=== Running unit tests ==="; \
	  $(PYTEST) $(PYTEST_Q) $(UNIT_DIR) $(PYTEST_WARN) $(PYTEST_XDIST) $(PYTEST_TIMEOUT) $(PYTEST_COV); \
	  echo "$new_sig" > $(UNIT_SIG); \
	  touch $@; \
	else echo "No changes detected; skipping unit tests."; fi

test: $(UNIT_STAMP)
	@echo "✅ Unit tests up-to-date"

test-all:
	$(PYTEST) $(PYTEST_Q) $(PYTEST_WARN) $(PYTEST_COV)

clean-tests:
	rm -rf $(STAMPS_DIR)

# -----------------------------------------------------------------------------#
# Build & Publish
build:
	$(PYTHON) -m pip install -U build
	$(PYTHON) -m build

upload: build
	$(PYTHON) -m pip install -U twine
	twine check dist/*
	twine upload dist/*

# -----------------------------------------------------------------------------#
# Version & Release helpers (setuptools_scm + Git tags)

LAST_TAG := $(shell git tag --list "v[0-9]*.[0-9]*.[0-9]*" --sort=-version:refname | head -n 1 || echo v0.0.0)
MAJOR    := $(shell echo "$(LAST_TAG)" | sed -E 's/^v([0-9]+)\..*/\1/')
MINOR    := $(shell echo "$(LAST_TAG)" | sed -E 's/^v[0-9]+\.([0-9]+)\..*/\1/')
PATCH    := $(shell echo "$(LAST_TAG)" | sed -E 's/^v[0-9]+\.[0-9]+\.([0-9]+)/\1/')

# -----------------------------------------------------------------------------#
# Version & Release helpers (setuptools_scm + Git tags)

version:
	@$(PYTHON) -m setuptools_scm || true

fetch-tags:
	git fetch --tags --force --prune 2>/dev/null || true

# Safety check: ensure no uncommitted or unstaged changes before tagging
check-clean:
	@if ! git diff --quiet || ! git diff --cached --quiet; then \
		echo "❌ Working directory not clean. Commit or stash changes before releasing."; \
		git status -s; \
		exit 1; \
	fi
	# Optional: ensure local branch is in sync with upstream
	@if [ "$$(git rev-parse @)" != "$$(git rev-parse @{u})" ]; then \
		echo "❌ Local branch not in sync with upstream (push/pull first)."; \
		exit 1; \
	fi

# Pick the highest semantic version tag (vX.Y.Z). Fallback to v0.0.0
LAST_TAG := $(shell git tag --list "v[0-9]*.[0-9]*.[0-9]*" --sort=-version:refname | head -n 1 || echo v0.0.0)
MAJOR    := $(shell echo "$(LAST_TAG)" | sed -E 's/^v([0-9]+)\..*/\1/')
MINOR    := $(shell echo "$(LAST_TAG)" | sed -E 's/^v[0-9]+\.([0-9]+)\..*/\1/')
PATCH    := $(shell echo "$(LAST_TAG)" | sed -E 's/^v[0-9]+\.[0-9]+\.([0-9]+)/\1/')

release-show: fetch-tags
	@echo "python exe:"; $(PYTHON) -c "import sys; print(sys.executable)"
	@echo "setuptools_scm version:"; $(PYTHON) -m setuptools_scm || echo "(unavailable)"
	@echo "installed dist version:"; $(PYTHON) -c "import importlib.metadata as m; print(m.version('sfdump'))" || echo "(package not installed)"
	@echo "Last Git tag: $(LAST_TAG)"

release-patch: fetch-tags check-clean
	NEW=v$(MAJOR).$(MINOR).$$(($$(printf '%d' $(PATCH)) + 1))
	git tag -a "$$NEW" -m "release: $$NEW"
	git push origin "$$NEW"
	@echo "Tagged $$NEW"

release-minor: fetch-tags check-clean
	NEW=v$(MAJOR).$$(($$(printf '%d' $(MINOR)) + 1)).0
	git tag -a "$$NEW" -m "release: $$NEW"
	git push origin "$$NEW"
	@echo "Tagged $$NEW"

release-major: fetch-tags check-clean
	NEW=v$$(($$(printf '%d' $(MAJOR)) + 1)).0.0
	git tag -a "$$NEW" -m "release: $$NEW"
	git push origin "$$NEW"
	@echo "Tagged $$NEW"

# -----------------------------------------------------------------------------#
# CLI convenience
ROOT ?= .
CLI_ARGS ?=
run-cli:
	sfdump $(ROOT) $(CLI_ARGS)

# -----------------------------------------------------------------------------#
clean:
	rm -rf build dist .eggs *.egg-info .coverage htmlcov .pytest_cache
	find . -type d -name "__pycache__" -prune -exec rm -rf {} +
	rm -rf $(STAMPS_DIR)
